// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZ7xvL9UEMSSGYsHjuCxDt-K2zN0H8EI',
    appId: '1:1029058971251:web:3a4d302ebe7b4f3eac4c06',
    messagingSenderId: '1029058971251',
    projectId: 'profeshv2',
    authDomain: 'profeshv2.firebaseapp.com',
    storageBucket: 'profeshv2.firebasestorage.app',
    measurementId: 'G-ELB14S9347',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyTidXqrgBnmQ-vmprS2Y5QRf3JlXFpI',
    appId: '1:1029058971251:android:2f803e29f5c63ce0ac4c06',
    messagingSenderId: '1029058971251',
    projectId: 'profeshv2',
    storageBucket: 'profeshv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrD_S0p-EFQFMF3Vfn6LeisxsJgCB8YdU',
    appId: '1:1029058971251:ios:726000e0895d0ba0ac4c06',
    messagingSenderId: '1029058971251',
    projectId: 'profeshv2',
    storageBucket: 'profeshv2.firebasestorage.app',
    iosBundleId: 'com.example.profeshForms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrD_S0p-EFQFMF3Vfn6LeisxsJgCB8YdU',
    appId: '1:1029058971251:ios:726000e0895d0ba0ac4c06',
    messagingSenderId: '1029058971251',
    projectId: 'profeshv2',
    storageBucket: 'profeshv2.firebasestorage.app',
    iosBundleId: 'com.example.profeshForms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEUyhLv0Rvf3XOXdmMr32f84JVbCL_9to',
    appId: '1:1029058971251:web:50a7e59011704104ac4c06',
    messagingSenderId: '1029058971251',
    projectId: 'profeshv2',
    authDomain: 'profeshv2.firebaseapp.com',
    storageBucket: 'profeshv2.firebasestorage.app',
    measurementId: 'G-VQWVY09SBZ',
  );
}
